### ISSUE TITLE
[Req] implement current node key getter

### ISSUE THREAD

**Issue by dalesbit** [KallynGowdy/angular2-firebase#15]
I recently came along to a problem, which case i needed the current child's key.
Coz, the docs is not full i dig into to code and realized that its much easier if i extend it with the following:

```
get rawPair():Observable<any> {
        return this.valueRaw.map((data) => {
            return {
                key:data[0].key(),
                value:data[0].val()
            }
        });
 }
```

So its not a good way to handle this problem, but it would be nice to have a way to access the key and not just the value.

regards, david

**Comment by KallynGowdy** [comment]
Just use `valueRaw` and use the `key()` and `val()` functions. It will work exactly the same as you expect.
