### ISSUE TITLE
Synchronized Array Support

### ISSUE THREAD

**Issue by KallynGowdy** [KallynGowdy/angular2-firebase#2]
Add Support for [Synchronized Arrays](https://www.firebase.com/blog/2014-05-06-synchronized-arrays.html) with Observables.
# API

The Synchronized Array API will provide easy handling of Firebase arrays for a specific Firebase Location.
### Creation

The API will be exposed via a `FirebaseArray` service that wraps a `FirebaseService`, which in turn wraps a `Firebase` SDK Object:

``` TypeScript
var firebase = new Firebase('https://SampleChat.firebaseIO-demo.com/users');
var service = new FirebaseService();
var arr = new FirebaseArray(service);

var otherArr = service.asArray();
```
### Manipulation

The `FirebaseArray` object will expose methods to _add_, _update_ & _remove_ child objects. In addition to calling the underlying service to complete these tasks, the methods also return promises that represent the async operations.

``` TypeScript
arr.add('hello').then(() => console.log('added!'));

arr.set(0, 'Hello, World!').then(() => console.log('set!'));

arr.remove(0).then(() => console.log('removed'));
```
### Observation

The `FirebaseArray` object will represent an observable object, providing the `subscribe()` method:

``` TypeScript
arr.subscribe(arrData => console.log('Array Updated: ', arrData));
```

Array Length observation will also be supported via the `.length` getter:

``` TypeScript
arr.length.subscribe(l => console.log('Array Length: ' + l));
```

The full observable will be accessible via the `arr.observable` property.

To access more refined members, such as the `child_added`, `child_removed`, `child_moved` and `child_changed` events, use a `FirebaseService` or the underlying `arr.service` object.
### Querying

The `FirebaseArray` object will provide a core set of querying capabilities against the array. 
These methods include:
- `filter()`, used to filter the arrays emitted by the observables.
- `map()`, used to transform the arrays emitted by the observables.
- `find()`, used to return a single value from the observed array.
- `indexOf()`, used to find the index of a given value.

Each of these methods follow the default implementations as specified in the Mozilla Developer Network for the [Array prototype](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array).
**All of the above methods will return observables.**

**Comment by eserlan** [comment]
Hi, great work with this project! I find it really useful! :smile: 

Though, I cant seem to find this feature in the distro, (from npm install), is that something you're planning on pushing sometimes soon?

**Comment by KallynGowdy** [comment]
Yes, I'm actually pushing the feature right now.
