### ISSUE TITLE
How to use authWithPassword

### ISSUE THREAD

**Issue by Znow** [KallynGowdy/angular2-firebase#4]
Hi

How could I use "authWithPassword" in my .ts file?

It doesn't seem to find it, either by using "Firebase.authWithPassword", or "FirebaseService.authWithPassword".

A more elaborated "quick guide", would be very much appreciated.

Kind regards

**Comment by KallynGowdy** [comment]
Hi Znow!

Not all Firebase SDK methods are exposed via the wrapper, so you have to use the native Firebase SDK client object. This object is exposed on a `FirebaseService` object via the `FirebaseService#firebase` property:

``` TypeScript
// as of v0.6.1
var ref = new Firebase("https://<YOUR-FIREBASE-APP>.firebaseio.com");
var service = new FirebaseService(ref);
alert("FirebaseService Firebase Instance is equal to ref: " + (service.firebase === ref));
```

For more documentation, make sure to visit the [Documentation Website](http://kallyngowdy.github.io/angular2-firebase/) that contains more examples and an extensive list of available properties and methods.

I am planning on improving the quick start, but I haven't been able to get to it in the recent days with Work and School.

I'm going to close this issue now. If you have a different question, please create a new issue, thanks.
