### ISSUE TITLE
TypeScript compilation error in firebase-array.ts

### ISSUE THREAD

**Issue by eserlan** [KallynGowdy/angular2-firebase#6]
Just thought I'd let you know about this one:

```
ERROR in <node>\firebase-angular2\src\firebase-array.ts
    (263,100): error TS2315: Type 'Subscription' is not generic.
```

**Comment by KallynGowdy** [comment]
Hey @eserlan, thanks for the input. I just looked at the issue, removed the generic typing, attempted to rebuild and got an error:

```
src/firebase-array.ts(263,100): 
    error TS2314: Generic type 'Subscription<T>' requires 1 type argument(s).
```

Are you sure that you are using the right TypeScript definition file? I use the `rxjs` (`node_modules/rxjs/Rx.d.ts`) TypeScript definition file in the project, which specifies that Subscription objects have a generic type parameter.

**Comment by KallynGowdy** [comment]
Because I haven't heard any additional feedback about this issue in the last couple of days, I am going to close this issue. If anything needs to be revisited, feel free to comment.
